server:
  port:
    8083
  servlet.context-path:
    /weatherapi  
spring:
  application:
    name: weatherservice
  profiles:
    active: dev
  main:
    allow-circular-references: true    
  mvc:
    pathmatch:
      matching-strategy:  ANT_PATH_MATCHER 
email: yaml@satish.com    
weather:
  api:
    appid: d2929e9483efc82c82c32ee7e02d563e
    mode: json
    units: metric